### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by grammaton** [spectra-music/spectra#39]
Can You Help me?

```
-- initialize_schema_migrations_table()
   -> 0.0089s
** Invoke db:structure:load_if_sql (first_time)
** Invoke db:create 
** Invoke environment 
** Execute db:structure:load_if_sql
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment 
** Execute db:abort_if_pending_migrations
rake aborted!
redirection forbidden: http://robohash.org/voluptateseaquedolorem.png -> https://robohash.org/voluptateseaquedolorem.png
/Users/giuseppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:223:in `open_loop'
/Users/giuseppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
/Users/giuseppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:704:in `open'
/Users/giuseppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:30:in `open'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/paperclip-4.2.0/lib/paperclip/io_adapters/uri_adapter.rb:17:in `download_content'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/paperclip-4.2.0/lib/paperclip/io_adapters/uri_adapter.rb:7:in `initialize'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/paperclip-4.2.0/lib/paperclip/io_adapters/http_url_proxy_adapter.rb:7:in `initialize'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/paperclip-4.2.0/lib/paperclip/io_adapters/registry.rb:29:in `new'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/paperclip-4.2.0/lib/paperclip/io_adapters/registry.rb:29:in `for'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/paperclip-4.2.0/lib/paperclip/attachment.rb:96:in `assign'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/paperclip-4.2.0/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:45:in `public_send'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:45:in `_assign_attribute'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:32:in `block in assign_attributes'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:26:in `each'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:26:in `assign_attributes'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/core.rb:453:in `init_attributes'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/core.rb:196:in `initialize'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
/Users/giuseppe/Git_REPO/spectra/db/seeds.rb:22:in `block (2 levels) in <top (required)>'
/Users/giuseppe/Git_REPO/spectra/db/seeds.rb:20:in `times'
/Users/giuseppe/Git_REPO/spectra/db/seeds.rb:20:in `block in <top (required)>'
/Users/giuseppe/Git_REPO/spectra/db/seeds.rb:18:in `times'
/Users/giuseppe/Git_REPO/spectra/db/seeds.rb:18:in `<top (required)>'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/railties-4.1.8/lib/rails/engine.rb:543:in `load_seed'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:200:in `load_seed'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:174:in `block (2 levels) in <top (required)>'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:240:in `call'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:240:in `block in execute'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:235:in `each'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:235:in `execute'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/giuseppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:199:in `each'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/giuseppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/task.rb:165:in `invoke'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:156:in `invoke_task'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:112:in `block (2 levels) in top_level'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:112:in `each'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:112:in `block in top_level'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:121:in `run_with_threads'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:106:in `top_level'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:84:in `block in run'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:182:in `standard_exception_handling'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/lib/rake/application.rb:79:in `run'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/gems/rake-10.4.0/bin/rake:33:in `<top (required)>'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/giuseppe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:seed
```

**Comment by toroidal-code** [comment]
`http` should have been `https` in the `db/seeds.rb` file. It was a redirection problem that appeared somewhere along the way. This has been fixed as of #40.

If you have any further problems, please create a new issue.
